---

# The directory to output the build to
target: build

# May be the name of any adapter in lib/adapters
adapter: base

# May be any language code in lib/languages
language: en

# An array of names of players found in lib/players
players: [flv, html, iframe, img, qt, swf, wmp]

# YES to include Sizzle.js, NO to exclude
css_support: YES

# YES to compress the code, NO to use the source code
compress: YES
